version: '3'

services:
  angular:
    build:
      context: ./angular-app
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build:
      context: ./spring-boot-app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: youssefDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
